id: IAD32298A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:25:13+00:00'
last_modified: '2022-06-08T05:54:00.942990+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6593
  title: ཨོ་རྒྱན་ཀུན་བཟང་ཆོས་འཁོར་གླིང་གི་འདོན་ཆ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EAA7:
      image_group_id: I1KG1399
      title: ''
      total_pages: 682
      order: 1
      base_file: EAA7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
